### ISSUE TITLE
Unsupported $module syntax detected in version.php of the mod_publication plugin.

### ISSUE THREAD

**Issue by nitro2010** [academic-moodle-cooperation/moodle-mod_publication#10]
Hello,

Please update your plugin for Moodle v3.0

While installating I get errors [all text with debugging option on]:

Unsupported $module syntax detected in version.php of the mod_publication plugin.
line 322 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()
Plugin mod_publication does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()

**Comment by phager-at** [comment]
We've got this issue fixed in the next release, but it'll take some time until it ran through our workflow and will be published.
The version for Moodle 3.0+ can take some time, because we're just updating to 2.9, after that and the implementation of new features we will adapt to 3.0.

**Comment by mkemmerling** [comment]
The outdated `$module` syntax in the version.php has been fixed in the master and MOODLE_28_STABLE branches (version 2015100803).
