### ISSUE TITLE
Importing data from assignment with group submission not working

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_publication#12]
Hi,

while testing your plugin a colleague from the HS Hannover found out that files will not be imported if the assignment was set to group submissions.
They had a closer look at the code and found out that it is due to the fact that Moodle saves submissions in group mode without any user relation:
> // For group submissions we don't immediately create an entry in the assign_submission table for each >user,
> // instead the userid is set to 0. In this case we use a different query to retrieve the grade for the user.

Copying each group submission to each of the group members into the publication plugin would also not be optimal as the files will be duplicated.
The best way would be to make a new view to represent group submissions in a correct way, e.g. display all group members in one row and then import their submission only once. So it's visible to everyone to whom the file is related to.

Even if this would mean too much changes and this won't be able to be implemented in the near future, the plugin should at least be optimized regarding to the aspect that group submissions aren't able to be selected. 
At the moment you can select them, import the files and then no files occur. So users are irritated and will contact the support saying that the plugin does not work correctly.

Cheers, 
Kathrin

**Comment by mkemmerling** [comment]
Hi Kathrin,

thanks for reporting this. I forwarded the issue to the developer to see what can be done to solve the issue.

**Comment by kaspot** [comment]
Thank you for your feedback – we just implemented for 2.9 that group assignments are listed in the dropdown but cannot be selected anymore. For the future, we want to map group assignments too, but not before 3.1 next term.

**Comment by Kathrin84** [comment]
I've seen that in the 3.1.1 version, this functionality is implemented and I would like to thank you for your work on this! 👍

**Comment by phager-at** [comment]
Thanks for giving such constructive feedback/inputs!
