### ISSUE TITLE
Add files button shown even if permission to upload files is prohibited

### ISSUE THREAD

**Issue by markchaneyuk** [academic-moodle-cooperation/moodle-mod_publication#14]
We have prohibited the authenticated user role from being able to upload/submit files. When a teacher logs in they still see the _Add Files_ button at the top of the mod/publication/view.php page. When they click this they then get a permission denied error. It would be nicer if the button wasnt shown at all?

Im guessing, as I have only had a really quick run through of the code, but line 207 (mod_publication_files_form.php) is where is checks if the publication is open, but should actually additionally check if the user has permission to do the upload? 

Moodle 2.7

**Comment by kaspot** [comment]
Thanks - it has been forwarded to our developer.

**Comment by phager-at** [comment]
We fixed this Issue back in the release for Moodle 2.8, if you update your system the mentioned behaviour should be corrected. You can also see this here: [https://github.com/academic-moodle-cooperation/moodle-mod_publication/issues/6](https://github.com/academic-moodle-cooperation/moodle-mod_publication/issues/6)
