### ISSUE TITLE
Feature Request: enable to share online submissions in the publication folder

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_publication#15]
Hi there,

this is a request from our teachers. At the moment, it's only possible to import submissions that are uploaded as files into the publication folder.
Within the assignment activity it's also possible to do submissions online via text.

It would be great if such online text submissions also could be imported into the publication folder.

Cheers,
Kathrin

**Comment by mkemmerling** [comment]
Hi Kathrin,

I forwarded your request to our developers. Since the publication folder is all about files this would probably require to create a file from the text submission–if possible.

Cheers,
Markus

**Comment by mkemmerling** [comment]
Our current plan is to implement this feature for the 3.2 version (to be released around March 2017).

**Comment by Kathrin84** [comment]
Hi Markus, 

thanks for your feedback. We're looking forward to it. :)

Cheers, Kathrin

**Comment by kaspot** [comment]
Hi Kathrin,
good news — it seems that this feature made it into the 3.2 version of our plugin. 
Please check out the newest version and let us know, what you think about it. 
Cheers, Kat

**Comment by Kathrin84** [comment]
Thank you for the implementation of this feature! +1
