### ISSUE TITLE
Notice: Undefined variable

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_publication#16]
Hi toghether,

while testing your new version, I git the following notice:
![publication_notice](https://cloud.githubusercontent.com/assets/4711883/16149314/3b6561ba-3490-11e6-80ff-a7be53aba701.png)

This is the code where the variable is missing:
$title = (has_capability('mod/publication:approve', $context)) ? $allfiles : $publication;

Cheers,
Kathrin

**Comment by mkemmerling** [comment]
Hi  Kathrin,
thanks for reporting. Does this affect v3.0.0 or also v2.9.2?

**Comment by Kathrin84** [comment]
Hi Markus,

sorry, it was my fault I did not specified this.
It's occurring with your latest plugin version 3.0.0 and we are testing with Moodle 3.0.4+ at the moment.

Cheers,
Kathrin

**Comment by mkemmerling** [comment]
Ok, thanks for the info.

**Comment by mkemmerling** [comment]
Hi Kathrin,

the bug has been fixed with version v3.0.1 (2016051101). Please update.

Cheers,
Markus
