### ISSUE TITLE
Inconsistent module naming in English language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [academic-moodle-cooperation/moodle-mod_publication#17]
Hi,

When I was translating your Student folder (mod_publication) plugin, I noticed that three strings use 'Publication' instead of 'Student folder' when rferring to this module name. I think it would be better to have a consistent naming for this module.

Can you please change the following three English language strings:
autoimport_help | publication
configautoimport | publication
nopublicationsincourse | publication

and replace 'into Publication module' for 'into Student folder module',
change 'into Publication instances' for 'into Student folder instances',
change 'There are no publication instances' for 'There are no Student folder instances''.

Thanks in advance for your help.

**Comment by kaspot** [comment]
Thanks for your feedback. 
We will check if these are really mistakes and if so we will fix them asap.

**Comment by phager-at** [comment]
Hi,

sorry for not updating this issue for so long. The language strings should be fixed from version 3.2.2 on (branches: MOODLE_32_STABLE with the latest stable version for Moodle 3.2 as well as master with the current development version for Moodle 3.3), so I'm closing this issue for now.

Thanks again for reporting the inconsistency to us!

cheers,
Philipp
