### ISSUE TITLE
Postgres support for groups

### ISSUE THREAD

**Issue by nino2205** [academic-moodle-cooperation/moodle-mod_publication#18]
We have a problem using mod_publication with postgres dbms and group mode within the moodle course.
The postgres log gives me following error:
`2017-03-22 13:03:58 CET ERROR:  column "grpq.groups" must appear in the GROUP BY clause or be used in an aggregate function at character 433
2017-03-22 13:03:58 CET STATEMENT:  SELECT
                        u.id,u.picture,u.firstname,u.lastname,u.firstnamephonetic,u.lastnamephonetic,u.middlename,u.alternatename,u.imagealt,u.email , u.email, u.username,
                                        COUNT(*) filecount,
                                        SUM(files.studentapproval) AS studentapproval,
                                        NULL AS teacherapproval,
                                        MAX(files.timecreated) AS timemodified , groups
                        FROM mdl_user u LEFT JOIN mdl_publication_file files ON u.id = files.userid AND files.publication = $1  LEFT JOIN (SELECT MAX(grps.courseid), MIN(grps.name) AS groups, grpm.userid AS userid
                                 FROM mdl_groups_members grpm
                            LEFT JOIN mdl_groups grps ON grps.id = grpm.groupid
                                WHERE grps.courseid = $2
                             GROUP BY grpm.userid
                             ORDER BY MIN(grps.name) ASC) AS grpq ON u.id = grpq.userid
                        WHERE u.id IN ($3,$4)
                        GROUP BY u.id,u.picture,u.firstname,u.lastname,u.firstnamephonetic,u.lastnamephonetic,u.middlename,u.alternatename,u.imagealt,u.email , u.email, u.username
                        ORDER BY lastname ASC LIMIT 10
`

On another system running with mysql as dbms, everything is working fine.

Can you confirm this issue?

**Comment by kaspot** [comment]
Hi, 
thanks for reporting this back to us. I don't think that this issue occurred in one of our instances. I will forward it to the developer to check it.

**Comment by phager-at** [comment]
Hello nino2205,

can you tell us, which version of Moodle and the mod_publication you used at the time the error occured? I think the error is very clear, just to check if we got all (supported) versions covered when fixing the error. Unfortunately I didn't notice this before. We're didn't have any automated tests (yet) for mod_publication and I develop locally with mariadb - which is a little bit more relaxed about GROUP BYs than postgres

cheers,
Philipp

**Comment by nino2205** [comment]
Hello Philipp,

we use Moodle 3.2.2+ and mod_publication v3.2.0 (2016120500). We also didn't notice that behaviour, since we changed our DBMS in December 2016 :)

cheers,
nino

**Comment by phager-at** [comment]
Hello Nino,

Thanks for the info! I'll get back to you, as soon as I have new information!

cheers,
Philipp

**Comment by mkemmerling** [comment]
The bug has been fixed with release v3.2.1, also published at [moodle.org](https://moodle.org/plugins/pluginversions.php?plugin=mod_publication).

Thanks again for reporting!
Marks Kemmerling

**Comment by nino2205** [comment]
Hello,
i have to thank you for very fast fixing!

regards,
nino
