### ISSUE TITLE
Bug in assignment import mode by accessing own submissions with Moodle 3.2

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_publication#19]
Hello,

I've encountered the following problem in Moodle 3.2:
I've created a publication activity wth the option to import submissions from an assignment activity.
In the connected assignment activity student A uploaded a file or entered an online text.
Now student A logs in and views this publication activity. On the view.php he can see his submission in the section "Own files". However, when he clicks on his own submission, following error message occurs:

![publication_error](https://cloud.githubusercontent.com/assets/4711883/25000930/6ca02ab8-2043-11e7-9af3-a8e72f9d3f6d.png)

Best regards, Kathrin

**Comment by phager-at** [comment]
Hi Kathrin,

thanks for reporting the issue! Seems like during adding of teamsubmission-support the file-permission checks got screwed up for some cases. I'll take a deeper look at it we get back to you ASAP!

cheers,
Philipp

**Comment by mkemmerling** [comment]
Hi Kathrin,

we just published version 3.2.2 of the mod_publication plugin (here and on moodle.org) that fixes this bug.

Thanks again for reporting!
Markus

**Comment by Kathrin84** [comment]
Hi Philipp and Markus,
thanks for fixing this bug!
Cheers, Kathrin
