### ISSUE TITLE
SQL error on PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-mod_publication#2]
mod_form.php, around line 76. It currently reads

     if(isset($this->current->id)){

which seems to evaluate to true when the activity is being added. On PostgreSQL this leads to SQL error (comparing integer field with empty string, which MySQL tolerates).
The solution that works for me is to replace the line with

    $filecount = 0;
    if(!empty($this->current->id)){

**Comment by relecand** [comment]
I can confirm this. Same error on Postgres. The workaround fixes the error.

**Comment by mkemmerling** [comment]
We are currently preparing a version for Moodle 2.8.5 which fixes the bug and has been checked by the code checker. It will be released in the next two months.

**Comment by mudrd8mz** [comment]
This seems to be fixed in the version 2015-06-24 (2015062400) of the plugin, thanks.

**Comment by kaspot** [comment]
Yes - just got the confirmation from our developer. Closing the issue.
