### ISSUE TITLE
Feature request: use filters to show uploads as sublists of various states (e.g., approved, pending, etc.)

### ISSUE THREAD

**Issue by frankiekam** [academic-moodle-cooperation/moodle-mod_publication#20]
Uploads are currently listed in a whole list that can be sorted by First / Surname, Username, Email, Last modified. However the list is always shown in its entirety. The list is shown based on the Option "Participants shown per page", which by default is 10 participants. So in a course where there are 30 participants, the list is shown over 3 pages. There is no filter the upload records into a sublist. 

Currently a teaching wanting to approve an upload has to sort the list by clicking on the Last modified column link TWICE. Only then will she see the latest uploads sorted in descending order. This is the fastest and most efficient way to work with the plugin if a teacher were to approve uploads in the fastest time possible. This way of working can be improved. 

To improve the usability of the plugin, I suggest these features:
(1) a "You have _N_ new unapproved uploads" status message displayed above the uploads list;
(2)  the uploads list, by default, be shown as ALL, and in descending order of last modified
(3), a filter that allows the user to display uploads in varying states: 
     "pending approval"
     "approved"
     "rejected/unapproved"
     "no files available"
     "all"
This will, IMHO, make the administrative task of approving uploads easier, more user-friendly and more manageable for the busy teacher or Moodle administrator.

**Comment by kaspot** [comment]
Thanks Frankie for the detailed information and the ideas you provided. I added this feature request to our tracking system to consider it for 3.4.

**Comment by goggo24** [comment]
We will make the column sortable and the user's last sort-setting will be stored permanently - that should help.

**Comment by goggo24** [comment]
Colum "teacherapproval" is now sortable - v.3.8.0+, hope that helps. During our development we have been confronted with the problem that state isn't a fied in the database. States is just a symbol for the selected value in teacherapproval - so sorting after that instead should improve the handling and come to the same result. Have fun!
