### ISSUE TITLE
Bug: Granting an extension causes fatal error

### ISSUE THREAD

**Issue by raad** [academic-moodle-cooperation/moodle-mod_publication#22]
Steps to reproduce:

1. Create a Student Folder activity in your course
2. Grant an extension to any Student
3. The listing breaks and an error message is displayed:

> Fatal error: Class 'mod_publication\local\allfilestable\html_writer' not found in /var/www/moodle/mod/publication/classes/local/allfilestable/base.php on line 349

Unfortunately, because the error is fatal, the rest of the page is not rendered and the user menu is stuck in a disabled state.
I have worked out the cause and will submit a pull request that fixes the issue.

**Comment by kaspot** [comment]
Thanks for reporting this - we will forward it to our developer.

**Comment by mkemmerling** [comment]
Fixed in v3.2.3 and v3.3.1.
