### ISSUE TITLE
Bug: Users without mod/publication:upload capability can't view publication activity

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_publication#24]
Hi,
a teacher told us that he cannot view the publication instance he created.

I did a research and found out that, the $table is only instantiated if a user has the capability to upload files to the folder. If not the if clause to init the table (https://github.com/academic-moodle-cooperation/moodle-mod_publication/blob/master/mod_publication_files_form.php#L96) will throw an a error without this capability.

This should of course not happen and we fixed this as a quick core fix in our instance - because otherwise our teacher could not use the plugin.

Here's our diff:

```
index 3cbe1ba..243a580 100644
--- a/mod/publication/mod_publication_files_form.php
+++ b/mod/publication/mod_publication_files_form.php
@@ -90,6 +90,17 @@ class mod_publication_files_form extends moodleform {
             $noticehtml .= html_writer::end_tag('div');
 
             $mform->addElement('html', $noticehtml);
+/* KIZ MODIFICATION START 
+   REASON: Bugfix: Teachers without mod/publication:upload capability can't view publication activity - LMS-1771 */
+            // Now we do all the table work and return 0 if there's no files to show!
+            if ($table->init()) {
+                $mform->addElement('html', \html_writer::table($table));
+            } else {
+                $mform->addElement('static', 'nofiles', '', get_string('nofiles', 'publication'));
+            }
+        }
+/* KIZ MODIFICATION END */
+/* ORIGINAL START
         }
 
         // Now we do all the table work and return 0 if there's no files to show!
@@ -98,6 +109,7 @@ class mod_publication_files_form extends moodleform {
         } else {
             $mform->addElement('static', 'nofiles', '', get_string('nofiles', 'publication'));
         }
+   ORIGINAL END */
 
         // Display submit buttons if necessary.
         if (!empty($table) && $table->changepossible()) {
```

Best, Kathrin

**Comment by phager-at** [comment]
Hi Kathrin, sorry for not responding that long!

Thank you for reporting that bug!
In the master branch (unpublished and prepared for 3.4) I myself fixed this bug - I wasn't aware of until now, due to my test-teachers always having the capability to upload files :)
The easiest fix would be to remove the `if (has_capability([..])) {` around the section instantiating the table-object. This is the way I'll go in 3.4, maybe we'll also backport that - I'll know more tomorrow evening.

cheers,
Philipp

**Comment by phager-at** [comment]
Hi again,

we fixed the issue in the current releases for Moodle 3.3 and 3.4 (namely v3.3.2 and v3.4.0)!
Thanks again for reporting!

Cheers,
Philipp
