### ISSUE TITLE
Bug: Wrong translation for allowedfiletypes(_help)

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_publication#26]
Hi,
I'm testing your plugin on our instance for Moodle 3.4.

I've encountered a translating bug which leads to a problem with using the allowed filetypes feature.

This is the instruction when I use English as my language:
![allowed_filetypes](https://user-images.githubusercontent.com/4711883/37278611-9d9982f8-25e8-11e8-9be6-48fbf8680775.png)
There the separator is a *comma* and filetypes should be declared *without* the point in front of the file type.

When I switch to the german version, I read this:
![allowed_filetypes_de](https://user-images.githubusercontent.com/4711883/37278695-d725c216-25e8-11e8-86a2-220517b28738.png)
I should use a *semicolon* and a point in front of the file type.

This leads to the error hint:
![wrong_signs](https://user-images.githubusercontent.com/4711883/37278729-f2fa70a4-25e8-11e8-8754-63d1d917bf51.png)

I assume that the english version is the correct way, as it also won't display any errors.
However, if I take a look at AMOS, there's this original text for the 3.4 version saved:
> Allowed filetypes (;)
> Accepted file types can be restricted by entering a semicolon-separated list of mimetypes, e.g. 
> 'video/mp4; audio/mp3; image/png; image/jpeg', or file extensions including a dot, e.g. '.png; .jpg'. If 
> the field is left empty, then all file types are allowed.

There's something messed up.
So I won't contribute a corrected translation for the german version. It would be nice, if you could have a look at this tiny issue.

Best, Kathrin

**Comment by phager-at** [comment]
Hi Kathrin,

yes you're right! The english version ist correct! I'm gonna check and fix the German language File ASAP!

Thanks for reporting!

**Comment by phager-at** [comment]
Hi Kathrin,

Sorry for not getting back to you that long!
I just checked with our 3.4 and 3.5 installations and the content of the German version above is correct (also the english text should have the same content) and you shouldn't get any error when inserting file extensions with '.' in front (like in your example). Also you should have Moodle's filetype-selector there to use.
Has this error occured with a pre 3.4 version of mod_publication (v3.3.x or similar)?

Cheers,
Philipp

**Comment by goggo24** [comment]
Hey Katrin,
we just changed our german langstring workflow, so we just adapted our german langstrings to the english ones (v.3.5.+) and fixed your small hints. Thanks again for reporting!
