### ISSUE TITLE
Minor: Missing spaces in strings

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_publication#28]
Hi,

I've just encountered this minor thing:
![missing_spaces](https://user-images.githubusercontent.com/4711883/44460364-10b6c800-a60d-11e8-8dd9-71809dbc3914.png)

The strings in the groupapproval mode are missing some spaces.

However, the lang file seems to be correct:
https://github.com/academic-moodle-cooperation/moodle-mod_publication/blob/master/lang/en/publication.php#L99
https://github.com/academic-moodle-cooperation/moodle-mod_publication/blob/master/lang/en/publication.php#L100

Don't know why the spaces are not displayed...
In the 3.4 version on a Moodle 3.4 instance the spaces are displayed correctly. The issue arises with the 3.5 version on a 3.5 Moodle.

Best, Kathrin

**Comment by phager-at** [comment]
OK, so I have found the reason for the behaviour: the label-tag's child-elements get positioned using flexbox. By introducing html tags inside the label, the textnodes and html-tags with content respectively being seen as separate elements, who's whitespace before and after gets ignored. As next step they get positioned directly next to each other.
I'll think about how to solve this issue and if it has to be solved by mod_publication or should be solved via theme_boost and will get back to you soon!

Thanks again for reporting!

**Comment by goggo24** [comment]
We just delete the html tags, because there is at the moment no other solution. Spaces will appear from v.3.6.+. Thanks for reporting!
