### ISSUE TITLE
Separate Groups drop-down filter

### ISSUE THREAD

**Issue by skjackson1** [academic-moodle-cooperation/moodle-mod_publication#29]
We are using the Student Folder in a Moodle Course and have set the Group mode to 'Separate groups'.  When a Teacher views the folder and attempts to use the drop-down to view the folder contents of just one group, nothing happens. The only way that we have found to get the filter to activate on the page is to click the 'save approval' button on the bottom right.
![image](https://user-images.githubusercontent.com/47669504/52868414-2ed42f80-313b-11e9-8895-4695496e096e.png)

This is not the way that the Separate Groups function normally works and we only stumbled across this workaround.

Many thanks,

Sandy

**Comment by goggo24** [comment]
Thanks for reporting! We will change the behavior in one of the next releases.

**Comment by goggo24** [comment]
Fix included in publication v.3.6.1 - coming soon!
