### ISSUE TITLE
Localized German string inconsistent with English string, and pulls in image from external site

### ISSUE THREAD

**Issue by nicoroeser** [academic-moodle-cooperation/moodle-mod_publication#30]
On 2019-03-14 at 09:33 UTC, Ralf Krause &lt;ralf.krause@gmail.com&gt; accepted translation #27780 in AMOS. The translation had been handed in by @goggo24 . The change contains a string modification for `modulename_help`.

There have been several problems with the German string since the change:
1. The string contains HTML markup, while the English original does not. The English original should always be changed first, and the translations updated accordingly. Translations should not try to beautify something if it is not locale-specific.
2. The German translation refers to external documents on the web, in this case, on hosts `www.academic-moodle-cooperation.org` and `typo3.univie.ac.at`. There are several issues with this:
   1. Links contain a protocol, in some cases `http` instead of `https`. They should probably drop the protocol altogether, so that the same protocol is used which was used to open the Moodle instance in which a user is working. Another good possibility is to use only `https`.
   1. Links will break when external documents go away. Typical website administrators do not guarantee URI stability for the next 50 years. The information could be moved to the Moodle docs, which may be a bit more stable, and which may be the obvious place for users to look for help. Or perhaps the linked information could be moved into the help texts? (I have not read it, but assume it to be rather long.)
   1. The referenced images cause HTTP GET requests to the `typo3.univie.ac.at` site when course administrators work in their courses. In the worst case, their browsers are configured to send Referer headers. This has the same characteristics as a tracking pixel (“web bug”). The image content is not important anyway (just shows a document, or a play button). The images could be replaced with Font Awesome characters; Moodle comes with Font Awesome. The next best solution could be to deliver the images with the plugin, and reference them inside the Moodle instance where the plugin is installed (but this seems too much for the help text).

**Comment by goggo24** [comment]
We will have a look - thanks for reporting! At the moment we have only german documentation. In the moment we link the images to our own homepage, so the icons won't appear, but thanks for the feedback, we will try to find a "nicer" solution for the images (change to fontawesome icons or sth. like that). English documentation will follow with v.3.7.x. in some of our published AMC plugins.

**Comment by goggo24** [comment]
So,  we will replace the images from our website to fonteawesome icons and change everywhere the links to https. The links will still go to our website, but if the links are dead also the plugin won't be supported anymore - so no worry ;)
