### ISSUE TITLE
Improvement: Adjust the height of the table rows

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_publication#31]
Hi there,

users showed us that the table when displayed with buttons is displayed in a suboptimal way:
![publication_table](https://user-images.githubusercontent.com/4711883/61513455-67837800-a9fd-11e9-9e65-5abd0700494b.png)

Therefore the height of the rows should be optimized so that's easier to click the right button for the intended content.

Best, Kathrin

**Comment by goggo24** [comment]
Thanks for reporting! You are right - the layout is not optimal and can be optimized. We are just finishing/publishing v.3.7.0. We will include the fix of this bug in our next minor version - v.3.7.1. 
I'll keep you up to date about the progress :)

**Comment by Kathrin84** [comment]
Hi @goggo24,

thanks for the response and the prospect that it'll be fixed. 👍 

Best, Kathrin

**Comment by goggo24** [comment]
v.3.7.1 is published - have fun!

**Comment by abias** [comment]
Hi @goggo24 ,

I am sorry, but I don't see v3.7.1 yet on https://moodle.org/plugins/pluginversions.php?plugin=mod_publication. Is / was there some delay on your side after you posted that message?

Thanks,
Alex

**Comment by goggo24** [comment]
Hey, sorry - i just got the info, that a line in version.php got lost (maturity level) and so they published it only on github. Moodle.org is following soon!

**Comment by abias** [comment]
Any news, @goggo24 ?

**Comment by goggo24** [comment]
coming next week
