### ISSUE TITLE
Resources are loaded from typo3.univie.ac.at

### ISSUE THREAD

**Issue by spackmat** [academic-moodle-cooperation/moodle-mod_publication#33]
Hi,

I scanned our Moodle instance for externally loaded resources and found that this module references three files from typo3.univie.ac.at, when I am inside the edit mode of a course. It is https://typo3.univie.ac.at/fileadmin/user_upload/p_aec/Doku_Icons/cheatsheet_icon.svg and two times https://typo3.univie.ac.at/fileadmin/user_upload/p_aec/Doku_Icons/multimediatutorial_icon.svg, all three are icons shown within the help text inside the add-activity modal.

For now we'll patch that out in our instance as our privacy policy doesn't allow loading external resources, but we would be very pleased if those resources would be removed from the module or otherwise not loaded from an external source.

Thanks and greets!

**Comment by goggo24** [comment]
Thanks for reporting. We will remove the link to our own doku in the german langstrings via amos and so no external ressource will be loaded anymore.

**Comment by spackmat** [comment]
Perfect, thank you!
