### ISSUE TITLE
Typo in capability name publication:recieveteachernotification + No capability name in language pack

### ISSUE THREAD

**Issue by abias** [academic-moodle-cooperation/moodle-mod_publication#34]
Hi all,

There is a typo in the capability name publication:recieveteachernotification (see https://github.com/academic-moodle-cooperation/moodle-mod_publication/blob/master/db/access.php#L83) which should rather read publication:receiveteachernotification.

Additionally, the corresponding string for the capability name is missing in the language pack (see https://github.com/academic-moodle-cooperation/moodle-mod_publication/blob/master/lang/en/publication.php#L42-L46).

I think the world can live with the typo in the capability name. But I would like to ask you to add the string to the language pack to get rid of debugging warning.

Thanks,
Alex

**Comment by goggo24** [comment]
Thanks for reporting. We will include the fix in v.3.7.1. - coming soon!

**Comment by goggo24** [comment]
v.3.7.1 now includes the langstring - the warning shouldn't appear anymore, but I just noticed that a small error slipped through - there is still a small type error (receive vs. recive). Coming soon!

**Comment by abias** [comment]
Thank you, Eva, for publishing this fix in 3.7.1.

As a small note:
You have now fixed the typo in the capability name, but did not provide an upgrade script in db/upgrade.php.

You should be aware that all installations on which the assignments of mod/publication:recieveteachernotification have been diverged from the defaults, mod/publication:receiveteachernotification will now be assigned just to the default roles again.
