### ISSUE TITLE
[BUG] Setting "Participants shown per page" to a high number causes lags and fatal errors

### ISSUE THREAD

**Issue by yorickreum** [academic-moodle-cooperation/moodle-mod_publication#35]
Good afternoon from Germany,

we ran into an issue where a student accidentally had set the number of participants shown per page to 11111 – this caused an infinite loading lag for him. Therefore he wasn't able to change this setting by himself anymore.
We were able to reproduce this problem on our testing server (although with much shorter lag time). Setting this setting to a much higher value (we tested 999999999) ended up with "Fatal error: Allowed memory size exhausted".
This should be caught / the setting should be limited to a reasonable limit.

We tested this in an environment with Moodle 3.7, mod_publication on branch MOODLE_37_STABLE and the current version of theme "Fordson".

Kind regards
Yorick

**Comment by goggo24** [comment]
Thanks for reporting. A possible solution that comes to my mind is to prohibit the manual entering of numbers and specify certain options (all, 10, 20, 50, 100) via dropdown as like in assignment. I will discuss it within the AMC and let you know, what we decide.

**Comment by goggo24** [comment]
Since v.3.8.1. pagination is now fixed to predefined values (all/10/20/50/100).
