### ISSUE TITLE
[QUESTION] Moodle 3.8 Compatibility

### ISSUE THREAD

**Issue by sulzer** [academic-moodle-cooperation/moodle-mod_publication#36]
Does v3.7.1 work with Moodle 3.8?  If not, are there any plans to make the plugin compatible anytime soon?  Thank you!

**Comment by goggo24** [comment]
It  should work with 3.8. too. In the next weeks (at the latest middle of february) we will publish the v.3.8.0. of all our plugins, which are missing. At the moment we are doing the final tests :)
