### ISSUE TITLE
Omit manager in recieveteachernotification cap 

### ISSUE THREAD

**Issue by christianwolters** [academic-moodle-cooperation/moodle-mod_publication#38]
Hi Hannes, dear contributors,

I propose that the manager role does not have the capability "mod/publication:recieveteachernotification" by default,
because a manager is usually not involved in day to day activities and should therefor not be bothered by notifications.

Best regards
Christian

**Comment by goggo24** [comment]
Of course not, manager shouldn't receive any mails - thanks also for the pull request. As soon as the stress of home-learning at our universities gets less, we will have a look!

**Comment by christianwolters** [comment]
Hi Eva,

thank you for picking up this issue and of course, there is no need to hurry.
(I like the term home-learning - was thinking about distanced learning ;-) )

fwiiw: I am still open for discussing this issue, maybe there is a use case for managing roles to be notified somewhen? One could add a hint into the readme file for manually adding the capability to further roles.

Cheers
Christian

**Comment by paaskynen** [comment]
Hi,

Experiencing the same issue. In our sites (Moodle 3.8) the manager role is reserved for support staff, who have no business receiving these messages.

Rgrds,
Paul.

**Comment by christianwolters** [comment]
Hi amc-team,

any chance getting my pr into producation,
I already forgot about this issue and ran into it again this week.

Best regards
Christian

**Comment by goggo24** [comment]
Hey Christian, i thought we've already corrected this behaviour - i will have a look! If not, we will include it for 3.10.. Cheers Eva

**Comment by goggo24** [comment]
It's already included in v.3.10 - the version should be published soon, we are just doing the final tests ;)
