### ISSUE TITLE
notifications of approbation to student send the wrong status + translation of approbation negation is missing

### ISSUE THREAD

**Issue by CamilleTrd** [academic-moodle-cooperation/moodle-mod_publication#41]
1. notification : approbation status is wrong

The notification email the student receives inverses the actual approbation status. 
If I **approve** my student file it sends the following notification email to the student : 
`Admin User has changed the approval status of 'test.pdf' for 'student folder' to not approved on 31 July 2020 at 1:06 pm`

2. translation of non approbation is hard coded

furthermore the "not" in "not approved" is hard coded and so renders the translation impossible in other language.
I will post asap my fix which adds a string for "not" and inverses the notification approbation status (ligne 78 in view.php).

But a cleaner fix will be to use the term "rejected" instead of "not approved". 
For example in french "non approuvé" is not something we say, but it is understandable. So to keep my fix "light" I didn't go further than translating the negation.

**Comment by nino2205** [comment]
We have the same situation and some teachers are confused about the mails they received.
A short official fix would be nice.

**Comment by goggo24** [comment]
Thanks for reporting - we will have a look.

**Comment by goggo24** [comment]
we've fixed it in v.3.10.0 - coming soon!
