### ISSUE TITLE
Version for Moodle 3.9.1

### ISSUE THREAD

**Issue by simoneidenskog-kmh** [academic-moodle-cooperation/moodle-mod_publication#42]
Hi!

We have been using "Student folder" at the Royal College of music in Stockholm for about two years now.

Before we updated to Moodle 3.9.1 we've noticed that the plugin only support Moodle 3.8. While we tried
it on Moodle 3.9.1, we noticed old instances of students folders created with Moodle 3.8 show uploads and
correct filenames. However the links are broken so teachers and students can't access the files. 

We haven't tried to create new Student with Moodle 3.9 so we don't know if this issue is isolated with 3.8 
or not.

We would appreciate a new version of Student folder supported by 3.9.

Best regards

Simon Eidenskog,
system manager Moodle at Royal College of music in Stockholm

**Comment by goggo24** [comment]
The publication version for Moodle 3.9. is nearly finished and it should be published next week.

**Comment by simoneidenskog-kmh** [comment]
Great! Do you know if it is a specific day for publish?

**Comment by goggo24** [comment]
already published - have fun ;) Cheers, Eva
