### ISSUE TITLE
Latest version v3.9.0 is marked as MATURITY_ALPHA

### ISSUE THREAD

**Issue by abias** [academic-moodle-cooperation/moodle-mod_publication#43]
Hey all,

while upgrading our Moodle to 3.9, I stumbled upon the fact that the v3.9.0 version of this plugin is marked as MATURITY_ALPHA in the Moodle plugin repo (see https://moodle.org/plugins/pluginversion.php?id=22330). That's why it is not automatically offered as update within Moodle (unless the admin decided to accept alpha plugin updates).

May I ask: Is this intented? If yes: Why? If not: Do you want to fix it?

Cheers,
Alex

**Comment by goggo24** [comment]
Of course not - it unfortunately slipped through. We will correct is - it's MATURITY_STABLE ;)
