### ISSUE TITLE
Proposal: UX improvements for "teacher view"

### ISSUE THREAD

**Issue by christianwolters** [academic-moodle-cooperation/moodle-mod_publication#44]
Hi amc-team,

consider the use case in which only a few students of possibly hundreds should upload something into the studentfolder

In this use case (especially for new users) it is not immediately clear, who has uploaded somthing 
and who has not and the teacher is presented with multiple instances of "No files availabe" statements:
* in the "Own files" area
* as well as in the "All files" table (except if an upload was performed by someone who is at the beginning of the table)

I'd like touse this issue to discuss possible solution and ask if you have discussed this use case before.

**Proposal 1**

Regarding interface consistency it could be helpful to treat both ares (own files and table) as equally important by using an additional heading above the table. E.g.:

![grafik](https://user-images.githubusercontent.com/2005580/99553420-67fb9c80-29be-11eb-9b42-949ef2298e71.png)

**Proposal 2**

In Addition to proposal 1 there could be an instance setting for the activity that sets a default sorting order for the table,
so that the all files table could always be sorted by "last modified" or one of the other columns.

What do you think?

Best regards
Christian

**Comment by goggo24** [comment]
Thanks Christian for your suggesstions. You are definitely right, that both areas are equally important. I will take your proposals to our backlog refinemet and will discuss it with the team.

**Comment by goggo24** [comment]
changed with v.3.11.3 - both area are now equally important.
