### ISSUE TITLE
Possible bug: Page rendering stops at the files table head with high files per page setting

### ISSUE THREAD

**Issue by spackmat** [academic-moodle-cooperation/moodle-mod_publication#46]
Hi,

we have a student, who cannot see the table with the uploaded files inside a study folder activity. I logged in with his account and could reproduce that, even in a fresh course with a fresh study folder activity. When no file is uploaded, he can see the table with headers and all as expected. When at least one file exists and should be shown in the table, the whole page rendering stops at the first `<th>` of the files table: This is what I see at the very end of the page's source: `<table cellspacing="0" class="flexible publications" id="attempts" width="100%"><thead><tr>` (with the tr closed empty instead of having those attributes `class="header c0" scope="col"`)

I checked the access rights of the user, but they are the same as other users. The user also states, he doesn't have any other issue and no other user reported such a problem, his teammates all can see the files, so does my trainer account. This happens in a real course as well as in an empty test course, but as far as I can see only with study folder activities.

Sony any ideas why the rendering of the whole page stops at that position for any user?

Edit: In the code of the base.php, I saw that the state of the table is persisted on a per-user basis. I logged in as the user again and visited the empty study folder where I can see the whole table. There I saw that in the options, the limit for the table was set to 10.000 and after setting that back to 10, the table got rendered again with files in it. So I see a bug here where setting the table limit to a very high value, the whole table cannot be rendered afterwards and with that resetting the value can only be done in an empty table. I am not that within the Moodle codebase, so I cannot say if this is a common problem or only occurs with mod_publication.

**Comment by goggo24** [comment]
Do you mean the option "Participants shown per page" for the pagination? If yes, with v.3.8.1 we set predefined values (all/10/20/50/100) for the setting.

**Comment by spackmat** [comment]
@goggo24 Yes, I think that't the field I am takling about (it's named differently in german). Then I have to wait until our hosting updates our campus wide moodle instance and the bug is already mitigated.

Nevertheless: Weird that the whole page stops rendering at that place, when the perPage-value for a user is set too high, but there aren't that many files present at all. One file is enough to trigger that crash.
