### ISSUE TITLE
mod/publication/view.php is loading very slowly due to missing index

### ISSUE THREAD

**Issue by rub-moodle-its** [academic-moodle-cooperation/moodle-mod_publication#47]
In a course with more than 700 students the overview page mod/publication/view.php is loading very slowly due to a missing index.

Please add an index on column "publication" for table "publication_files" to speed things up.

**Comment by goggo24** [comment]
Thanks for your feedback. We have planned it for the next version.

**Comment by goggo24** [comment]
Index is included in v.3.11.0 - coming this weekend.
