### ISSUE TITLE
Ambiguous column name 'email'.

### ISSUE THREAD

**Issue by mrkskwsnck** [academic-moodle-cooperation/moodle-mod_publication#55]
I am maintaining Moodle v3.9.11 running mod_publication v3.9.0 based on SQL Server (MSSQL) database.

A **teacher** gets the following error by entering the student folder activity → _Ambiguous column name 'email'._

![image](https://user-images.githubusercontent.com/486983/142651631-56ebf79c-a32e-4952-90f1-5be8b5d24901.png)

I figured out, the problem results from the doubled `u.name` column (with aliased table prefix) addressed within the `SELECT` statement. Because of that the `ORDER BY` statement can′t decide which one to order by, because the `email` column lacks its aliased table prefix.

**Comment by mrkskwsnck** [comment]
I created the PR https://github.com/academic-moodle-cooperation/moodle-mod_publication/pull/56 with a hacky fix

**Comment by goggo24** [comment]
included in v.3.11.2 - thanks for the PR
