### ISSUE TITLE
Error message when Student Folder gets files from Assignment new attempt and selecting Update files

### ISSUE THREAD

**Issue by cdipe** [academic-moodle-cooperation/moodle-mod_publication#59]
To reproduce:
1. Student folder is set to get files from an assignment, and not auto sync files
2. Student uploads file to the assignment, this is visible to teacher in Student Folder after selecting _Update files_.
3. Student gets new attempt in the assignment, and uploads new files there
4. Teacher selects _Update files_ in Student Folder, gets error message **ERROR: The registration_created event must define objectid and object table.**

Using Moodle 3.9 and StudentFolder 3.9.0

**Comment by goggo24** [comment]
We will have a look if the error also occurs under 3.11. 
@cdip nevertheless would you be able, to provide us  the error message when debugging is activated? Thanks.

**Comment by cdipe** [comment]
I was thinking of another thing as well, but not sure if it's a bug: When the student folder is set to auto-sync files from an assignment, the button "update files" are still visible. Obviously, since this report is for when using that ;) 
But shouldn't the files be updated automatically anyway?

**Comment by goggo24** [comment]
So the error message appears, when you press the button - right? The button should be visible & is not necessary. But it works as a kind of fallback if the automatically synchronisation isn't working, you can press the button and manually start the synchronisation.

**Comment by goggo24** [comment]
fixed with v.3.11.3
