### ISSUE TITLE
Capability mod/publication:upload issue

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_publication#6]
Hi there,

as I don't want teachers to upload files to the folder, I took them the above mentioned capability away. However, nothing changed in the UI. There was stll the section "Own files" and and the button to add files.

I think this section should not appear if a user does not has the capability to upload files to the activity.

Kind regards,
Kathrin

**Comment by mkemmerling** [comment]
Hi Kathrin,

thanks for reporting this issue. We forwarded it together with your pull request #7 to our developer.

**Comment by mkemmerling** [comment]
This has been fixed in the master and MOODLE_28_STABLE branches (version 2015100803).
