### ISSUE TITLE
Overlapping text

### ISSUE THREAD

**Issue by ralfhilg** [academic-moodle-cooperation/moodle-mod_publication#60]
![2022-03-01_12h20_56](https://user-images.githubusercontent.com/41056305/156890760-fccadc52-a438-4514-9868-412439db0993.png)

In Moodle 3.9 texts are overlapping if a submission date is set. 
Theme Boost. 
Checked with several browsers.

**Comment by goggo24** [comment]
I'm sorry, I cannot reproduce the bug. When I try it with v3.9.0 (2020061500) and Moodle Core 3.9.7 and Standard Boost it looks fine => ![grafik](https://user-images.githubusercontent.com/16721900/161816001-f35e13b8-8901-42f3-91e8-9491d790f430.png)

**Comment by goggo24** [comment]
Since we have not received any feedback so far, I will close the issue. If the erros still occurs, please reopen it.
