### ISSUE TITLE
No local language in date settings

### ISSUE THREAD

**Issue by cdipe** [academic-moodle-cooperation/moodle-mod_publication#62]
Using Student folder 3.11.2 in Moodle 3.11.6

The date / time setting does not follow language settings

<img width="827" alt="image" src="https://user-images.githubusercontent.com/14754240/169279519-32f5a196-1224-4934-ad43-fbe1badd461d.png">
<img width="846" alt="image" src="https://user-images.githubusercontent.com/14754240/169279542-5555f0fb-225c-4aec-b27e-cc4d57ae3ed2.png">

**Comment by cdipe** [comment]
@goggo24 you are right, the dates are displayed in English format also there. So the problem is elsewhere.

**Comment by goggo24** [comment]
@cdipe this FAQ might help=> https://docs.moodle.org/311/en/Language_FAQ#I.27ve_set_a_default_site_language.2C_but_the_Moodle_calendar_is_in_English._Why.3F

**Comment by cdipe** [comment]
@goggo24 Thank you!
