### ISSUE TITLE
Error while manually updating entries from assignment

### ISSUE THREAD

**Issue by gitopandi** [academic-moodle-cooperation/moodle-mod_publication#66]
Dear developers,

we (University in Germany) configured the student folder for adding entries from an assignment with manual update. Now we have error message during the update process and updating the student folder isn't possible anymore. I don't have a clue whats going on. I assume there might be problems with deleting of entries. We use the student folder since 2019 and did not have this issue in the past. We are on Moodle 3.9.16+ and 
$plugin->version = 2020061500;
$plugin->requires = 2020061300;
$plugin->component = 'mod_publication';
$plugin->maturity = MATURITY_STABLE;
$plugin->release = "v3.9.0"; 
The three screenshots showing the error messages with and without activation of the debug mode in Moodle.

![CleanShot 2022-09-16 at 08 18 02@2x](https://user-images.githubusercontent.com/97835433/190590390-7ec74854-f465-46ad-a9c5-ec54e2a2993d.png)
![CleanShot 2022-09-16 at 08 17 26@2x](https://user-images.githubusercontent.com/97835433/190590398-0fcc32b5-7c5a-4b91-8b57-7e325f4ea839.png)

The message is shown immediately after clicking on continue after the confirmation dialog
![CleanShot 2022-09-16 at 08 17 18@2x](https://user-images.githubusercontent.com/97835433/190590529-71d3f831-6728-4be1-8035-2162e61950ed.png)

Any ideas where to look? 
And thank you very much in advance for any help
Andreas

**Comment by goggo24** [comment]
Thank for reporting, we will have a look.

**Comment by goggo24** [comment]
Sorry for the delay. Fixed with v.3.9.1. - version coming soon!

**Comment by mkemmerling** [comment]
Just published v.3.9.1. Thanks again for reporting.
