### ISSUE TITLE
Incompatibility with Moodle 4.3

### ISSUE THREAD

**Issue by zimmersi** [academic-moodle-cooperation/moodle-mod_publication#73]
Hi,

I have updated my moodle instance to version 4.3 and now the student folders are missing.
When is an updated version expected to be made available?

Kind regards,
Silvio

**Comment by goggo24** [comment]
Hey Silvio,

what do you mean with the student folders are missing? I've just used a v.4.2.x of studenfolder with moodle core 4.3.0 and the activity is there and works fine. Regarding v.4.3.0 - we we will start work soon.

Regards, Eva

**Comment by zimmersi** [comment]
Hey Eva,
thanks for your reply.
first of all, I m not a moodle pro just the server admin. ;-)
After updating moodle to v4.3 I see that mod_publication is deactivated and I can not see a way to activate it again. That's why I assumed that the plugin is incompatible with moodle v4.3

mod_publication is on version 2023081001

regards, Silvio

**Comment by goggo24** [comment]
Strange, what happens if you click on the eye icon? Can you add a screenshot, where you try to activate it. Thanks

**Comment by zimmersi** [comment]
I can not see an eye icon in my plugin overview
![grafik](https://github.com/academic-moodle-cooperation/moodle-mod_publication/assets/74589100/dff0e7b5-1e02-4c2b-8501-647b645b4e5d)

**Comment by goggo24** [comment]
That means that the code of studenfolder isn't there anymore, only the database tables exists. You have to install the code again, if you want to use it or complete the uninstall process.

**Comment by zimmersi** [comment]
ah okay, where can I find it? I have created a backup before updating.

**Comment by zimmersi** [comment]
okay, got it, thanks. the english version is more clear here: missing from disk!
