### ISSUE TITLE
Does not update files

### ISSUE THREAD

**Issue by cdipe** [academic-moodle-cooperation/moodle-mod_publication#79]
Moodle 4.1.8, Student Folder v4.1.1 2022121201
Group assigment. First submission was published as expected, but when a submission was reverted to draft and updated, the first submission is still showing in the Student folder. The button **Update files** makes no difference.

**Comment by mwreichel** [comment]
Hi @cdipe,
we already had a closer look on that and this bug is already fixed in the current version of the plugin.
Due to that we won't fix it for previous versions.

**Comment by cdipe** [comment]
Hi @mwreichel 
do you know if the 4.2.2 version is compatible with moodle 4.1.10?

**Comment by moniNaydenov** [comment]
Hi @cdipe ,

technically, yes, you can use it, but:
1. in version.php, you have to change the `$plugin->requires = 2023042400;` to `$plugin->requires = 2022112800;`
2. in moodle 4.1, you don't have the secondary navigation in the header of the activity, so you'll have to use the "Student folder administration" menu to get to the "File submissions" tab, and the breadcrumb to get back to the activity's main page:
![moodle4 1](https://github.com/academic-moodle-cooperation/moodle-mod_publication/assets/1238023/7f52d4cb-5864-45d8-8fa9-0beaaa591d84)
![moodle4 2](https://github.com/academic-moodle-cooperation/moodle-mod_publication/assets/1238023/4fc9d16f-8dc2-4907-a29b-35008cf7ff06)

Apart from that, after some testing, it seems to be working fine :)

Good luck!

**Comment by cdipe** [comment]
@moniNaydenov , thank you!!
