### ISSUE TITLE
New monologo activity icon for Moodle 4.4

### ISSUE THREAD

**Issue by monnardj** [academic-moodle-cooperation/moodle-mod_publication#80]
In Moodle 4.4, activity icons have been redesigned. They are still 24 x 24, but the content is smaller and doesn't fill the entire space. The icon for student folder should be modified accordingly.
<img width="213" alt="image" src="https://github.com/academic-moodle-cooperation/moodle-mod_publication/assets/5880250/65a042e7-e4de-4925-9914-bd1773c02690">

**Comment by mwreichel** [comment]
Hi @monnardj,
thank you for your issue.
We already designed a new version of the icon, which will be part of the next version of the plugin.

Martin
