### ISSUE TITLE
Add option to display uploaded documents only to the student who upload it

### ISSUE THREAD

**Issue by abowman-unige** [academic-moodle-cooperation/moodle-mod_publication#81]
Hello,

We would love to have to a feature that allows uploaded documents to be visible only to the student who uploaded them and teacher/manager/admin.

- Add a setting in the document upload settings interface where the teacher can choose if the document should be visible only to the uploader or everyone.
- Ensure that documents set to be private are only accessible to the uploader and authorized personnel.

Thank you

**Comment by mwreichel** [comment]
Hi @abowman-unige ,
thank you for your feature request. We'll have a closer look on that.

All the best,
Martin

**Comment by abowman-unige** [comment]
Hi @mwreichel,
any update if this enhancement would be possible?
Regards,
Allan

**Comment by mwreichel** [comment]
Hi @abowman-unige,
please excuse my late answer to your request.

This topic was discussed internal in the meantime.
Why you don't use the assignment activity for this use case? There it is a main feature that participants see only their own submissions and users with the right to edit the course/ the activity see all of them.
If there's the need to publish participants submissions using the student folder too, you could import them from the assignment at any time.

As the feature is already available within another activity, we won't implement this at ours.

We kindly ask for your understanding.

All the best,
Martin
