### ISSUE TITLE
After update to 4.4.0 I get Undefined constant "PUBLICATION_APPROVAL_GROUPAUTOMATIC" on admin-pages

### ISSUE THREAD

**Issue by baltaner** [academic-moodle-cooperation/moodle-mod_publication#84]
Hi,
after updating to version 4.4.0 my admin pages show
"Fehler: Undefined constant "PUBLICATION_APPROVAL_GROUPAUTOMATIC""

Moodle works, Plugin works also, but moodle/admin shows this error message

PHP 8.1
Version 4.4.1+ (Build: 20240802)

**Comment by nelliemuller** [comment]
I'm getting the same for 4.4.

**Comment by Benjamin-unige** [comment]
Same issue, the constants used in the settings.php file of the plugin are not defined, or rather moodle cannot find where they are defined.
Adding `require_once(__DIR__ . '/locallib.php');` after the `if ($ADMIN->fulltree) {` (line 31) in settings.php fix the issue

**Comment by mwreichel** [comment]
Hi,
thanks for reporting this bug. We will publish a version including a bugfix asap.
Sorry for any inconvenience.

All the best,
Martin

**Comment by kalisp** [comment]
> I need the fix urgently as I cannot use the admin. Any idea when the new upgrade will be ready?

That fix by Benjamin-unige works, its just pasting single line to `mod/publication/settings.php`

**Comment by baltaner** [comment]
Thank you Benjamin-unige, the fix works for me.

**Comment by mwreichel** [comment]
Hi,
@Benjamin-unige thank you for your contrubiton and to @lucaboesch for preparing the pull-request. The fixed version should be available in a few minutes.

Once again apologising for any inconvenience caused by this.

Cheers,
Martin

**Comment by nelliemuller** [comment]
Yes, the fix by Benjamin works. Thank you for your quick reply and help.
