### ISSUE TITLE
PUBLICATION_APPROVAL_GROUPAUTOMATIC

### ISSUE THREAD

**Issue by corti** [academic-moodle-cooperation/moodle-mod_publication#86]
Exception : Undefined constant "PUBLICATION_APPROVAL_GROUPAUTOMATIC"
hello, I have just upgraded Moodle to the latest version 4.4+ and I get this message whenever I try accessing the admin zone.
Cheers, diego

**Comment by goggo24** [comment]
Thanks for reporting. Have you used v.4.4.1 of the plugin? We released a new version yesterday at 17:17 with the fix. 
Does it work now? Eva
