### ISSUE TITLE
German translation: Freigabe vs Zustimmung

### ISSUE THREAD

**Issue by ralf-krause** [academic-moodle-cooperation/moodle-mod_publication#87]
Dear developers,
I am the maintainer of the german Moodle language packs. Yesterday I got a new translation from Julia Laßnig. She wants to change the german wording "Zustimmung" which is currently used for the plugin mod_publication. She wants to use "Freigabe" instead of "Zustimmung".

She writes the following:
_____
Hallo Ralf,
laut perplexity.ai ist der Unterschied zwischen Zustimmung und Freigabe:
Zustimmung: Juristischer Begriff, der Einverständnis mit einem Rechtsgeschäft beschreibt, das entweder vor oder nach dem Abschluss des Geschäfts gegeben wird.
Freigabe: Allgemeiner Begriff für die Erlaubnis oder Genehmigung zur Durchführung einer Aktion oder Nutzung von Ressourcen, oft in technischen oder administrativen Kontexten verwendet.

Duden hat bei den Verben die bessere Bedeutungsbeschreibung:
zustimmen: mit etwas einverstanden sein; etwas billigen, gutheißen, akzeptieren
freigeben: nicht mehr zurückhalten, zur Verfügung stellen / der Öffentlichkeit, dem freien Gebrauch übergeben

In beiden Fällen finde ich, dass Freigabe es in diesem Zusammenhang besser trifft. Soll ich trotzdem ausbessern?

Danke!
LG Julia
_____

Yes, I think it's a very good idea. Please let us change the wording.

Best regards,
Ralf

Ralf Krause
moodleSCHULE e.V.

[publication.txt](https://github.com/user-attachments/files/16550700/publication.txt)

**Comment by mwreichel** [comment]
Hi @ralf-krause,

thank you for contacting us.
We'll discuss the request internally and get back to you.

All the best,
Martin

**Comment by mwreichel** [comment]
Hi @ralf-krause,
we'll change the wording in German to "Freigabe". We've checked this and in most other plugins it is used at the moment. Before our big changes in the last releases, we used both in a similar way.
I checked the attached langstrings and added missing one's, where also "Zustimmung" etc. was used.
Therefore, and with further adjustments to the langstrings (and to fit some Moodle core phrases), we've prepared new langstrings, which I will upload in a few minutes to AMOS.

A big thank you to Julia Laßnig, for coming up with this idea.

Cheers,
Martin
